stages:
  - build
  - deploy
  - cleanup
variables:
  CONTAINER_IMAGE: pepe:${CI_COMMIT_SHORT_SHA}

build:
  stage: build
  script:
    - sudo docker buildx build --platform linux/amd64 --rm -t ${CONTAINER_IMAGE} .
  only:
    - main
  tags:
    - pepe

deploy:
  stage: deploy
  needs: [build]
  script:
    - cat "$ENV_LOCAL" > .env.local
    - sudo docker compose -f docker-compose.yml down
    - sudo TAG=${CI_COMMIT_SHORT_SHA} docker compose up -d
  after_script:
    - rm -rf ./*
  only:
    - main
  tags:
    - pepe

cleanup:
  stage: cleanup
  needs: [deploy]
  script:
    - rm -rf ./*

build_public:
  stage: build
  needs: [build]
  when: manual
  script:
    - sudo docker buildx build --platform linux/amd64 --rm -t ${CONTAINER_IMAGE} .
  only:
    - main
  tags:
    - public-p3p3

deploy_public:
  stage: deploy
  needs: [build_public]
  script:
    - cat "$ENV_PRODUCTION" > .env.production
    - sudo docker compose -f docker-compose.production.yml down
    - sudo TAG=${CI_COMMIT_SHORT_SHA} docker compose -f docker-compose.production.yml up -d
  after_script:
    - rm -rf ./*
  only:
    - main
  tags:
    - public-p3p3

cleanup_public:
  stage: cleanup
  needs: [deploy_public]
  script:
    - rm -rf ./*

deploy_public_first_time:
  stage: deploy
  needs: [build_public]
  when: manual
  script:
    - sudo TAG=${CI_COMMIT_SHORT_SHA} docker compose -f docker-compose.production.yml up -d
  after_script:
    - rm -rf ./*
  only:
    - main
  tags:
    - public-p3p3
